export const Types = {
  poa: [
    "laranja",
    "verde",
    "verde limão",
    "amarelo",
    "azul",
    "azul bebe",
    "pink",
    "rosa",
    "vermelho",
    "violeta",
    "preto",
    "marinho",
    "marrom c rosa",
    "rosa c marrom",
    "azul c marrom",
    "vermelho c preto",
    "pink c preto",
    "onça pink",
    "onça (ocre c preto)",
    "tifani",
    "pipoca",
    "listrado"
  ],
  liso: [
    "laranja",
    "verde",
    "verde limão",
    "amarelo",
    "azul",
    "azul bebe",
    "pink",
    "rosa",
    "vermelho",
    "violeta",
    "preto",
    "marinho",
    "branco",
    "kraft",
    "amarelo ouro",
    "champagne",
    "rosa claro",
    "neon amarela",
    "neon verde",
    "neon pink",
    "neon laranja"
  ],
  temas: [
    "coroa",
    "game",
    "laço",
    "estrela",
    "aranha",
    "homem verde",
    "coroa azul",
    "coroa rosa",
    "ratinho",
    "mulher poderosa",
    "mon bola",
    "mon laranja",
    "mon azul",
    "mon amarelo",
    "Festa junina",
    "tifani",
    "unicornio",
    "prata",
    "fazendinha",
    "vaquinha",
    "laço pink",
    "circo",
    "chuva",
    "melancia",
    "ouro"
  ]
}
